name: renqing_ledger
description: A Flutter app for a personal renqing ledger.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.5.1
  google_mlkit_text_recognition: ^0.13.0
  image_cropper: ^9.1.0
  image_picker: ^1.0.4
  file_picker: ^8.1.2
  http: ^1.6.0
  paddle_ocr:
    path: packages/paddle_ocr
  path_provider: ^2.1.2
  share_plus: ^10.1.1
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
